

List<String> getLyrics() {
  return ['Puedo saber de ti con solo tocarte',
  'Puedo saber si tú quieres saber de mí',
  'Debemos perdonar para poder amarnos',
  'Y equilibrarnos para unirnos con las estrellas',
  'Puedes pintar lo que quieras en estos Óleos',
  'Transparentes',
  'Para poder sanar tu corazón',
  'Gente diferente',
  'Con amor, con amor',
  'Mente diferente',
  'Con amor, con amor',
  'Abrimos otra vez el portal de las eras',
  'Recuperare ahí todo lo que perdí',
  'Debemos perdonar para poder amarnos',
  'Y equilibrarnos para unirnos con las estrellas',
  'Puedes pintar lo que quieras en estos Óleos',
  'Transparentes',
  'Para poder sanar tu corazón',
  'Gente diferente',
  'Con amor, con amor',
  'Mente diferente',
  'Con amor, con amor',
  'Viví el tiempo real con el mantra',
  'Estar contigo',
  'Viví el tiempo real con el mantra',
  'Estar contigo',
  'Viví el tiempo real con el mantra',
  'Estar contigo',
  'Viví el tiempo real con el mantra',
  'Estar contigo.'];
}